version: '3.8'
services:
  app:
    image: nguyentientai/class-cicd:latest
    container_name: class-cicd-app
    ports:
      - "5005:5005"
    env_file:
      - .env                 
    restart: unless-stopped 